### ISSUE TITLE
Types abstraits

### ISSUE THREAD

**Issue by Stefane-paris** [Naufrage7Inc/advanced-programmation-game#1]
Pour les types abstraits les usages veulent que les types abstraits soient suffixés. Par exemple, le type `Coords` s'écrient usuellement `coords_t` (ou pour les puristes du français` t_coords` :-)
Voyant le TA `size` je les écrirais plutôt `size_t` et `coordiante_t`.

**Comment by Naufrage7** [comment]
On a utilisé la première lettre en majuscule comme convention car [size_t](http://en.cppreference.com/w/c/types/size_t) est déjà utilisé par exemple :/

**Comment by Stefane-paris** [comment]
Oui !!! Restez avec cette convention.  :-]

**Comment by Naufrage7** [comment]
Parfait!
